name: Enforce Branch Policy

on:
  pull_request:
    branches:
      - main

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
    - name: Check if the PR is from allowed branches
      run: |
        if [[ ! ${{ github.head_ref }} =~ ^(development|release/.*)$ ]]; then
          echo "Error: Pull requests into 'main' must come from 'develop' or 'release/*' branches."
          exit 1
        fi
      shell: bash
